name: Push image
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Print name
          run: echo "Hello, I am deploying ${{ inputs.chartType }}"
          
      

