name: Push image
on:
  workflow_dispatch:  
  workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Print name
          run: echo "Hello from first app"
          
      

